Repository pycodehash/pycodehash, pull requests merged in 2023-12, with the labels that each got.

#46 CICD: GitHub Releases config
  .github/release.yml
Labels: cicd

#47 REL: Release of PycodeHash v0.2.0
  src/pycodehash/version.py
Labels: maintenance

#50 ENH: SQL find table references
  src/pycodehash/sql/references.py
  tests/sql/test_references.py
Labels: enhancement

#49 ENH: Add functionality to hash Python dependencies through their version
  README.md
  docs/dependencies.md
  example_dependency.py
  src/pycodehash/dependency/__init__.py
  src/pycodehash/dependency/dependency.py
  tests/dependency/test_dependency.py
Labels: enhancement

#52 ENH: visitors for SQL enriched table references
  src/pycodehash/sql/__init__.py
  src/pycodehash/sql/ast_visitor.py
  src/pycodehash/sql/references.py
  tests/sql/test_references.py
Labels: enhancement

#54 CICD: require at least one label for a PR
  .github/workflows/pr_labels.yml
Labels: cicd

#53 DOC: include Python Dependencies in docs
  mkdocs.yml
Labels: documentation

#55 REL: version bump
  src/pycodehash/version.py
Labels: maintenance

#62 FIX: HiveTableHash backwards compatibility
  src/pycodehash/datasets/hive.py
Labels: bug

#59 MAINT: move Python-function-related functionality to own module
  pyproject.toml
  src/pycodehash/__init__.py
  src/pycodehash/hashing.py
  src/pycodehash/preprocessing/__init__.py
  src/pycodehash/python_function/__init__.py
  src/pycodehash/python_function/decorator_stripper.py
  src/pycodehash/python_function/docstring_stripper.py
  src/pycodehash/python_function/function_stripper.py
  src/pycodehash/python_function/hashing.py
  src/pycodehash/python_function/lines_transformer.py
  src/pycodehash/python_function/stores.py
  src/pycodehash/python_function/tracing.py
  src/pycodehash/python_function/transfomers.py
  src/pycodehash/python_function/typehint_stripper.py
  src/pycodehash/python_function/unparse.py
  src/pycodehash/python_function/utils.py
  src/pycodehash/python_function/whitespace_normalizer.py
  tests/__init__.py
  tests/python_function/__init__.py
  tests/python_function/standalone.py
  tests/python_function/test_decorator_stripper.py
  tests/python_function/test_hashing.py
  tests/python_function/test_preprocessing.py
Labels: maintenance

#61 ENH: support CTE expressions for SQL reference detection
  src/pycodehash/sql/references.py
  tests/sql/test_references.py
Labels: enhancement

#63 REL: bump to v0.4.0
  src/pycodehash/version.py
Labels: maintenance
